### ISSUE TITLE
[BUG] Plugin won't load on 1.19

### ISSUE THREAD

**Issue by PovilasLT** [NikV2/CombatPlus#14]
**Describe the bug**
PLugin wont work on Paper 1.19

**To Reproduce**
Load plugin on 1.19

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Paper 1.19, latest build

**Additional Information (Optional)**
`[14:48:34 ERROR]: Error occurred while enabling CombatPlus v1.6.5 (Is it up to date?)
java.lang.ClassCastException: class org.bukkit.configuration.MemorySection cannot be cast to class java.lang.Boolean (org.bukkit.configuration.MemorySection is in unnamed module of loader java.net.URLClassLoader @5c29bfd; java.lang.Boolean is in module java.base of loader 'bootstrap')
        at me.nik.combatplus.files.Config$Setting.getBoolean(Config.java:240) ~[CombatPlus-1.6.5 (1).jar:?]
        at me.nik.combatplus.modules.impl.DisableOffhand.<init>(DisableOffhand.java:22) ~[CombatPlus-1.6.5 (1).jar:?]
        at me.nik.combatplus.CombatPlus.onEnable(CombatPlus.java:102) ~[CombatPlus-1.6.5 (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:309) ~[PlugManX (7).jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:120) ~[PlugManX (7).jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugManX (7).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2147) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-51]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:48:34 INFO]: [CombatPlus] Disabling CombatPlus v1.6.5
`

**Comment by NikV2** [comment]
Delete your config and let it reset.
